apiVersion: apps/v1
kind: Deployment
metadata:
  name: coll-0f069a686e7b49d6afbc721b9f66c46e-depl
  labels:
    app: coll-0f069a686e7b49d6afbc721b9f66c46e
    release: prometheus  # Added label for PodMonitor discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coll-0f069a686e7b49d6afbc721b9f66c46e
      release: prometheus  # Added label for PodMonitor discovery
  template:
    metadata:
      labels:
        app: coll-0f069a686e7b49d6afbc721b9f66c46e
        release: prometheus  # Added label for PodMonitor discovery
    spec:
      containers:
        - name: coll-0f069a686e7b49d6afbc721b9f66c46e
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:coll-0f069a686e7b49d6afbc721b9f66c46e
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http  # Optional for HTTP traffic
            - containerPort: 7070 #same as the deployed code
              name: metrics  # Added port for metrics scraping