apiVersion: v1
kind: Service
metadata:
  name: coll-0f069a686e7b49d6afbc721b9f66c46e-srv
spec:
  selector:
    app: coll-0f069a686e7b49d6afbc721b9f66c46e
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
  type: ClusterIP